### ISSUE TITLE
extrinsic calibration result 

### ISSUE THREAD

**Issue by Chatoyant19** [keenan-burnett/radar_to_lidar_calib#1]
Hi, please tell me whether the calibration result is 2D or 3D?
In general, the extrinsic between two sensors need to be represented by 6 DOF, of which, rotation needs at least 3 quantities to represent.
I calculate the rotation and translation by running calibrate.py
my result is here:
rotation index: 697 rotation: 0.8089601082993712 radians, 46.349999999999966 degrees
delta_x: [-0.596] delta_y: [0.4172]
rotation index: 696 rotation: 0.816814089933346 radians, 46.79999999999999 degrees
delta_x: [0.298] delta_y: [-0.5364]
rotation index: 697 rotation: 0.8089601082993712 radians, 46.349999999999966 degrees
delta_x: [1.0728] delta_y: [-2.6224]
rotation index: 696 rotation: 0.816814089933346 radians, 46.79999999999999 degrees
delta_x: [0.4172] delta_y: [0.5364]
rotation index: 697 rotation: 0.8089601082993712 radians, 46.349999999999966 degrees
delta_x: [-0.4172] delta_y: [0.596]
rotation index: 696 rotation: 0.816814089933346 radians, 46.79999999999999 degrees
delta_x: [0.9536] delta_y: [0.1192]
rotation index: 697 rotation: 0.8089601082993712 radians, 46.349999999999966 degrees
delta_x: [-0.596] delta_y: [0.]
rotation index: 696 rotation: 0.816814089933346 radians, 46.79999999999999 degrees
delta_x: [-0.8344] delta_y: [-0.4768]
rotation index: 696 rotation: 0.816814089933346 radians, 46.79999999999999 degrees
delta_x: [-0.3576] delta_y: [0.2384]
rotation index: 695 rotation: 0.82466807156732 radians, 47.24999999999996 degrees
delta_x: [0.4172] delta_y: [-0.2384]
rotation: 0.8144578954431534 radians, 46.66499999999998 degrees
x: 0.03576 y : -0.19668000000000002 z : 1.0
why is the rotation a 1D value and translation a 2D vector in the here?
By the way, I used the example data in your readme.md file.

**Comment by keenan-burnett** [comment]
It's 2D. Note that the Navtech radar's output is a 2D scan. The 3D Velodyne point cloud is projected onto a top-down 2D view. The two images are then correlated using the Fourier-Mellin transform to get a 2D transform. 2D transforms only have 1 parameter for rotation, and 2 parameters for translation.

**Comment by Chatoyant19** [comment]
> The 3D Velodyne point cloud is projected onto a top-down 2D view.

ok, i see, thank you very much.
